sudo: required
dist: trusty
language: generic
env:
    global:
        - "BUILD_NUMBER=$TRAVIS_BUILD_NUMBER"
        - "BUILD_DIR=$TRAVIS_BUILD_DIR"
        - "TRAVIS_MSBUILD_MODE=framework"
        - "TRAVIS_MSBUILD=./travis-msbuild"
        - "TRAVIS_MSBUILD_BIN=$TRAVIS_MSBUILD/bin"
        - "TRAVIS_MSBUILD_FRAMEWORK=$TRAVIS_MSBUILD/lib-dotnet"
        - "PATH=$PATH:$TRAVIS_MSBUILD_BIN"
before_install:
    - git clone https://github.com/0x0ade/travis-msbuild.git
    - chmod a+x "$TRAVIS_MSBUILD_BIN"/msbuild-prepare
    - msbuild-prepare
script:
    - msbuild /p:Configuration=Release
